// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZdhkaXeko_fRWgxfQOxAOYi7eT5XPs8',
    appId: '1:91795987118:web:8d8c85c4d9a419a4b02b3f',
    messagingSenderId: '91795987118',
    projectId: 'expanse-tracker-19ce8',
    authDomain: 'expanse-tracker-19ce8.firebaseapp.com',
    storageBucket: 'expanse-tracker-19ce8.firebasestorage.app',
    measurementId: 'G-5KZ7RLC0DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofvbdMeHfQ6yrE7XhiA1TTWwFajrexqU',
    appId: '1:91795987118:android:4b65629a8161502eb02b3f',
    messagingSenderId: '91795987118',
    projectId: 'expanse-tracker-19ce8',
    storageBucket: 'expanse-tracker-19ce8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyly8OvPnz8sNryrZnMqqEmH5QWvMiwSE',
    appId: '1:91795987118:ios:61e633f42bac9cedb02b3f',
    messagingSenderId: '91795987118',
    projectId: 'expanse-tracker-19ce8',
    storageBucket: 'expanse-tracker-19ce8.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyly8OvPnz8sNryrZnMqqEmH5QWvMiwSE',
    appId: '1:91795987118:ios:61e633f42bac9cedb02b3f',
    messagingSenderId: '91795987118',
    projectId: 'expanse-tracker-19ce8',
    storageBucket: 'expanse-tracker-19ce8.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAZdhkaXeko_fRWgxfQOxAOYi7eT5XPs8',
    appId: '1:91795987118:web:a850d869bc062664b02b3f',
    messagingSenderId: '91795987118',
    projectId: 'expanse-tracker-19ce8',
    authDomain: 'expanse-tracker-19ce8.firebaseapp.com',
    storageBucket: 'expanse-tracker-19ce8.firebasestorage.app',
    measurementId: 'G-VCRM0PQGJ4',
  );
}
